name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//04NveqsvqhM8mCgYIARAAGAQSNwF-L9IrtSOdU74pP6xtfexPIb_TeAtY-pJi2NjxEGR3ALS9gcotlvNIK8IRzWcivk-FZtaIVt0
